name: Create release

on:
  pull_request:
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run Release
        run: yarn release-it -c .release-it.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
